export enum CelestialErrorCode {
  // Vault
  VAULT_NOT_FOUND            = 'VAULT_NOT_FOUND',
  VAULT_ALREADY_EXISTS       = 'VAULT_ALREADY_EXISTS',
  VAULT_LOCKED               = 'VAULT_LOCKED',
  VAULT_WRONG_PASSWORD       = 'VAULT_WRONG_PASSWORD',
  VAULT_CORRUPT              = 'VAULT_CORRUPT',
  VAULT_DECRYPT_FAILED       = 'VAULT_DECRYPT_FAILED',
  VAULT_ENCRYPT_FAILED       = 'VAULT_ENCRYPT_FAILED',

  // Account
  ACCOUNT_NOT_FOUND          = 'ACCOUNT_NOT_FOUND',
  ACCOUNT_ALREADY_EXISTS     = 'ACCOUNT_ALREADY_EXISTS',
  ACCOUNT_LIMIT_REACHED      = 'ACCOUNT_LIMIT_REACHED',

  // Chain / network
  CHAIN_UNSUPPORTED          = 'CHAIN_UNSUPPORTED',
  CHAIN_RPC_ERROR            = 'CHAIN_RPC_ERROR',
  CHAIN_SWITCH_REJECTED      = 'CHAIN_SWITCH_REJECTED',
  NETWORK_TIMEOUT            = 'NETWORK_TIMEOUT',
  NETWORK_ERROR              = 'NETWORK_ERROR',

  // Transaction
  TX_SIGNING_FAILED          = 'TX_SIGNING_FAILED',
  TX_BROADCAST_FAILED        = 'TX_BROADCAST_FAILED',
  TX_INSUFFICIENT_FUNDS      = 'TX_INSUFFICIENT_FUNDS',
  TX_GAS_ESTIMATION_FAILED   = 'TX_GAS_ESTIMATION_FAILED',
  TX_REJECTED_BY_USER        = 'TX_REJECTED_BY_USER',
  TX_SIMULATION_FAILED       = 'TX_SIMULATION_FAILED',
  TX_NONCE_TOO_LOW           = 'TX_NONCE_TOO_LOW',
  TX_REPLACEMENT_UNDERPRICED = 'TX_REPLACEMENT_UNDERPRICED',

  // dApp
  DAPP_UNAUTHORIZED          = 'DAPP_UNAUTHORIZED',
  DAPP_REJECTED              = 'DAPP_REJECTED',
  DAPP_METHOD_UNSUPPORTED    = 'DAPP_METHOD_UNSUPPORTED',
  DAPP_CHAIN_MISMATCH        = 'DAPP_CHAIN_MISMATCH',

  // CEX
  CEX_AUTH_FAILED            = 'CEX_AUTH_FAILED',
  CEX_RATE_LIMIT             = 'CEX_RATE_LIMIT',
  CEX_ORDER_FAILED           = 'CEX_ORDER_FAILED',
  CEX_CREDENTIALS_NOT_FOUND  = 'CEX_CREDENTIALS_NOT_FOUND',
  CEX_INVALID_SYMBOL         = 'CEX_INVALID_SYMBOL',
  CEX_INSUFFICIENT_BALANCE   = 'CEX_INSUFFICIENT_BALANCE',

  // Messaging
  MESSAGE_UNKNOWN_TYPE       = 'MESSAGE_UNKNOWN_TYPE',
  MESSAGE_TIMEOUT            = 'MESSAGE_TIMEOUT',
  MESSAGE_INVALID_PAYLOAD    = 'MESSAGE_INVALID_PAYLOAD',

  // Bot engine
  BOT_STRATEGY_NOT_FOUND     = 'BOT_STRATEGY_NOT_FOUND',
  BOT_EXECUTION_FAILED       = 'BOT_EXECUTION_FAILED',
  BOT_SLIPPAGE_EXCEEDED      = 'BOT_SLIPPAGE_EXCEEDED',
  BOT_CIRCUIT_BREAKER        = 'BOT_CIRCUIT_BREAKER',

  // Generic
  INTERNAL_ERROR             = 'INTERNAL_ERROR',
  NOT_IMPLEMENTED            = 'NOT_IMPLEMENTED',
  VALIDATION_ERROR           = 'VALIDATION_ERROR',
  UNAUTHORIZED               = 'UNAUTHORIZED',
}

export interface CelestialErrorMeta {
  code: CelestialErrorCode;
  message: string;
  context?: Record<string, unknown>;
}
